config/routes.rb
Rails.application.routes.draw do

  get 'ingredients/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :items, only: [:new, :create, :edit, :update, :destroy]
  resources :users do 
    resources :recipes, only: [:new, :create, :show, :edit, :update, :destory, :index]
  end
  resources :recipes, only: [:index, :create, :show, :edit, :destroy, :update] 

  resources :ingredients, only: [:index]
  
  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'
  root 'welcome#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
    has_one :recipe, through: :recipe_directions
    has_many :recipe_directions
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: { message: "must be present" }
    belongs_to :pantry
end

app/models/pantry.rb
class Pantry < ApplicationRecord
    belongs_to :user
    has_many :items
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: { message: "must be present" }
    belongs_to :user
    has_many :recipe_ingredients
    has_many :users, through: :comments
    has_many :ingredients, through: :recipe_ingredients
    has_many :recipe_directions
    has_many :directions, through: :recipe_directions

    accepts_nested_attributes_for :directions, allow_destroy: true
    accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: lambda { |attributes| attributes['name'].blank? }

    def self.latest
        where("created_at >=?", Time.zone.today.beginning_of_day)
    end
       
    def self.old
        where("created_at <?", Time.zone.today.beginning_of_day)
    end
end

app/models/recipe_direction.rb
class RecipeDirection < ApplicationRecord
    belongs_to :recipe 
    belongs_to :direction
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :recipe 
    belongs_to :ingredient
end
 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  has_one :pantry
  has_many :items, through: :pantry
  has_many :recipes
  

  after_save :create_and_associate_pantry

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  

  private

  def create_and_associate_pantry
    pantry = Pantry.create(user_id: self.id)
    pantry.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    if params[:name]
      @recipes = Recipe.joins(:ingredients).where("ingredients.name LIKE ?", "#{params[:name]}")
    else
      @recipes = Recipe.all
    end
    render :recipes
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :set_item, only: [:edit, :update, :destroy]

    def new
        @item = Item.new
    end

    def create 
        @item = Item.new(item_params)
        @item.pantry_id = current_user.pantry.id
        if @item.valid?
            @item.save
            redirect_to root_url
        else
            render :new
        end
    end

    def edit
    
    end

    def update
        @item.update(item_params)
        @item.save
        redirect_to root_url
    end

    def destroy
        @item.destroy
        redirect_to root_url
    end

    private

    def item_params
        params.require(:item).permit(
            :name,
            :amount
        )
    end

    def set_item
        @item = Item.find(params[:id])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]

    def index
        if params[:user_id]
            @recipes = User.find(params[:user_id]).recipes  
        elsif !params[:date].blank?
            if params[:date] == "Latest Recipes"
                @recipes = Recipe.latest
            else
                @recipes = Recipe.old
            end
        elsif params[:name]
            @recipes = Recipe.joins(:ingredients).where("ingredients.name LIKE ?", "#{params[:name]}")
        else
            @recipes = Recipe.all 
        end
    end

    def new
        @recipe = Recipe.new(user_id: params[:user_id])
        3.times { @recipe.ingredients.build }
        3.times { @recipe.directions.build }
    end

    def create 
        @recipe = Recipe.new(recipe_params)
        if @recipe.valid?
            @recipe.save
            redirect_to user_recipe_path(@recipe.user, @recipe)
        else 
            render :new
        end
    end

    def show
        
    end

    def edit
       
    end

    def update
        @recipe.update(recipe_params)
        if @recipe.save
            redirect_to user_recipe_path(@recipe.user, @recipe)
        else 
            redirect_to edit_user_recipe_path(@recipe)
        end
    end

    def destroy
        @recipe.destroy
        redirect_to root_url
    end

    private

    def recipe_params
        params.require(:recipe).permit(:name, :description, :user_id,
            ingredients_attributes: [:name, :amount, :_destroy],
            directions_attributes: [:step, :_destroy] 
        )
    end

    def set_recipe
        @recipe = Recipe.find(params[:id])
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
    <% if @recipe.errors.any? %>
        <div id="error_explanation">
            <h3> There are errors: </h3>
            <ul>
                <% @recipe.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.hidden_field :user_id %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :description %>
    <%= f.text_area :description %> <br>
    <br>
    <%= f.label :ingredients %> <br>
    <%= f.add_nested_fields_link :ingredients %><br>
    <%= f.nested_fields_for :ingredients do |ff| %>
        <%= ff.label :name %>
        <%= ff.text_field :name%> <br>

        <%= ff.label :amount %>
        <%= ff.text_field :amount %> <br>

        <%= ff.remove_nested_fields_link %>
    <% end %>
    <br>

    <%= f.label :Directions %> <br>
    <%= f.add_nested_fields_link :directions %><br>
    <%= f.nested_fields_for :directions do |ff| %>
        <%= ff.label :step %>
        <%= ff.text_area :step %> <br>

        <%= ff.remove_nested_fields_link %>
    <% end %>
    <br>
    
    
    <%= f.submit %>

<% end %>

app/views/recipes/_recipes.html.erb
<table class="center">
    <thead>
        <th> Name </th>
        <th> Description </th>
        <th> Options </th>
    </thead>
    <% current_user.recipes.each do |recipe| %>
        <tr>
            <td> <%= recipe.name %> </td>
            <td> <%= recipe.description %> </td>
            <td> <%= link_to 'Edit', edit_recipe_path(recipe) %></td>
            <td> <%= link_to 'Delete', recipe_path(recipe), method: 'delete' %></td>
        </tr>
    <% end %>
</table>

app/views/recipes/edit.html.erb
<h1>Edit This Recipe</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<h1> All Recipes </h1>
<%= form_tag("/recipes", method: "get") do %>
 
  <%= select_tag "date", options_for_select(["Latest Recipes", "Legacy Recipes"]), include_blank: true %>
  <%= submit_tag "Filter" %>
<% end %>
<%= form_tag recipes_url, method: :get do %>
    <label>Search Ingrediengts:</label><br>
    <%= text_field_tag :name, params[:name] %><br><br>
    <%= submit_tag "Search" %><br>
<% end %>
<ul>
    <% @recipes.each do |recipe| %>
        <li><%= link_to recipe.name, recipe_path(recipe) %>
    <% end %>
</ul>

app/views/recipes/new.html.erb
<h1>Create A New Recipe</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<p><%= @recipe.description %></p>
<h3>Recipe Ingredients</h3>
<ul>
    <% @recipe.ingredients.each do |ingredient| %>
        <li><%= ingredient.name %> - <%= ingredient.amount %></li>
    <% end %>
</ul>
<br>
<h3>Recipe Instructions</h3>
<ul>
    <% @recipe.directions.each do |direction| %>
        <li><%= direction.step %></li>
    <% end %>
</ul>

<%= link_to 'Edit Recipe', edit_user_recipe_path(@recipe.user, @recipe) %>
<%= link_to 'Delete Recipe', recipe_path, method: "delete"  %>

app/views/welcome/home.html.erb
    <h1 class="center"> Welcome, <%= current_user.email %>! </h1>

    <h2> What's In Your Pantry? </h2>

    <div>
    <% if current_user.pantry.items.empty? %>
        <h4> There are currently no items in your pantry. Click the link below to add items. </h4>
        <%= link_to 'Add Items To Pantry', new_item_path %>
    <% else %>
        <%= render partial: 'pantry/pantry' %>
        <%= link_to 'Add Items To Pantry', new_item_path %>
    <% end %>
    </div>

    <div>
    <h2> What Recipes Do You Have? </h2>
    <% if current_user.recipes.empty? %>
        <h4> You haven't created any recipes yet. Create a recipe or look at other recipes! </h4>
        <%= link_to 'Create A Recipe', new_user_recipe_url(current_user) %>
    <% else %>
        <%= render 'recipes/recipes' %><br>
        <br>
        <%= link_to 'Create A New Recipe', new_user_recipe_url(current_user) %> <br>
        <%= link_to 'View Your Recipes', user_recipes_path(current_user) %>
    <% end %>
</div>