config/routes.rb
Rails.application.routes.draw do

  get 'ingredients/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :items, only: [:new, :create, :edit, :update, :destroy]
  resources :users do 
    resources :recipes, only: [:new, :create, :show, :edit, :update, :destory, :index]
  end
  resources :recipes, only: [:index, :create, :show, :edit, :destroy, :update] 

  resources :ingredients, only: [:index]
  
  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'
  root 'welcome#home'

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    if params[:name]
      @recipes = Recipe.joins(:ingredients).where("ingredients.name LIKE ?", "#{params[:name]}")
    else
      @recipes = Recipe.all
    end
    render :recipes
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/index.html.erb
<%= form_tag ingredients_url, method: :get do %>
    <label>Search Ingrediengts:</label><br>
    <%= text_field_tag :name, params[:name] %><br><br>
    <%= submit_tag "Search" %><br>
<% end %>
    <ul>
        <% @recipes.each do |recipe| %>
            <li><%= link_to recipe.name , recipe_path(recipe) %></li>
        <% end %>
    </ul>